version: "3.8"

services:
  mc-site:
    image: python:3.11-slim
    container_name: mc-site
    restart: unless-stopped
    ports:
      - "8088:5000"
    volumes:
      - ./Site:/app
    working_dir: /app
    command: ["sh", "-c", "pip install Flask && python app.py"]
